# -*- coding: utf-8 -*-
"""firstDay.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TLeUYCck86jNxjONXpGssX0aWaW0fpPU
"""

d = {'a':'apple','b':'banana','c':{'d':'dog','e':'eggs','f':{'g':'gun'}}}

d1 = dict()

def get(d,key):
    for item in d:
        if type(d[item]) == dict:
            return get(d[item],key)
        else:
            d1[item] = d[item]
    return d1[key]
        
print(get(d,'e'))